

% simply kick out all answer-sets, where the number of filled fields
% does not match with colsum/rowsum.

:-  colsum(X, COLSUM),
    #count{ Element : filled(X, Element) } < COLSUM.

:-  colsum(X, COLSUM),
    #count{ Element : filled(X, Element) } > COLSUM.

:-  rowsum(Y, ROWSUM),
    #count{ Element : filled(Element, Y) } > ROWSUM.

:-  rowsum(Y, ROWSUM),
    #count{ Element : filled(Element, Y) } < ROWSUM.
