

container(c2, 1, 1). container(c2, 1, 3).
container(c2, 2, 1). container(c2, 2, 2). container(c2, 2, 3).
container(c2, 3, 1). container(c2, 3, 3). container(c2, 3, 4).
container(c2, 4, 1). container(c2, 4, 2). container(c2, 4, 3). container(c2, 4, 4).


colsum(1, 2).
colsum(2, 2).
colsum(3, 3).
colsum(4, 2).

rowsum(1, 1).
rowsum(2, 0).
rowsum(3, 2).
rowsum(4, 2).
rowsum(5, 4).

filled(1, 1).
filled(3, 3). filled(3, 4).
filled(4, 2). filled(4, 3).
filled(5, 1). filled(5, 2). filled(5, 3). filled(5, 4).