
% 4 columns
colsucc(1, 2).
colsucc(2, 3).
colsucc(3, 4).

% 5 rows
rowsucc(1, 2).
rowsucc(2, 3).
rowsucc(3, 4).
rowsucc(4, 5).

% containers (c1 .. c5)
container(c1, 1, 1).
container(c2, 3, 1).

container(c3, 2, 1). container(c3, 2, 2). container(c2, 2, 3).
container(c3, 3, 1). container(c3, 3, 3).
container(c3, 4, 1).
container(c3, 5, 1). container(c3, 5, 2). container(c3, 5, 3). container(c3, 5, 4).

container(c4, 4, 2). container(c4, 4, 3).
container(c5, 3, 4).

% colsums
colsum(1, 2).
colsum(2, 2).
colsum(3, 3).
colsum(4, 2).

% rowsums
rowsum(1, 1).
rowsum(2, 0).
rowsum(3, 2).
rowsum(4, 2).
rowsum(5, 4).

% expected results: 

% filled(1, 1).
% filled(3, 3). filled(3, 4).
% filled(4, 2). filled(4, 3).
% filled(5, 1). filled(5, 2). filled(5, 3). filled(5, 4).
